server:
    port: 7055
    servlet:
        context-path: /datalog
        register-default-servlet: true
        encoding:
            charset: UTF-8
            enabled: true
            force: true
        session:
            tracking-modes: COOKIE
    tomcat:
        uri-encoding: UTF-8
spring:
    application:
        name: risedata-log
    aop:
        auto: false
        proxy-target-class: false
    autoconfigure:
        exclude:
            - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
            - org.springframework.boot.autoconfigure.quartz.QuartzAutoConfiguration
            - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
            - org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration
            - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
    datasource:
        generate-unique-name: false
        type: com.alibaba.druid.pool.DruidDataSource
        druid:
            filter:
                stat:
                    log-slow-sql: true
                    mergeSql: true
                    slow-sql-millis: 3000
                wall:
                    config:
                        drop-table-allow: false
                    enabled: true
            stat-view-servlet:
                enabled: false
                url-pattern: /druid/*
                login-username: admin
                login-password: admin
                reset-enable: false
                allow: 127.0.0.1
            web-stat-filter:
                enabled: false
                url-pattern: /*
                exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*,/static/*'
            y9-public:
                #driver-class-name: oracle.jdbc.OracleDriver
                #url: jdbc:oracle:thin:@127.0.0.1:1521:orcl
                #username: Y9_PUBLIC
                #password: '111111'
                driver-class-name: com.mysql.cj.jdbc.Driver
                url: jdbc:mysql://localhost:3306/y9_data?serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true&useUnicode=true&characterEncoding=utf-8&rewriteBatchedStatements=true&useCompression=true&useSSL=false
                username: root
                password: '111111'
                initialSize: 1
                maxActive: 20
                maxPoolPreparedStatementPerConnectionSize: 100
                maxWait: 60000
                minEvictableIdleTimeMillis: 300000
                minIdle: 1
                poolPreparedStatements: true
                testOnBorrow: false
                testOnReturn: false
                testWhileIdle: true
                timeBetweenEvictionRunsMillis: 60000
                useGlobalDataSourceStat: true
                validationQuery: SELECT 1 FROM DUAL
    jmx:
        default-domain: risedata-log
    jpa:
        hibernate:
            naming:
                implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        open-in-view: false
        properties:
            hibernate:
                cache:
                    use_query_cache: false
                    use_second_level_cache: false
                dialect: org.hibernate.dialect.MySQL8Dialect
                #dialect: org.hibernate.dialect.Oracle10gDialect
                hbm2ddl:
                    auto: none
                jdbc:
                    batch_size: 100
                show_sql: false
    main:
        allow-bean-definition-overriding: true
    servlet:
        multipart:
            maxFileSize: 200MB
            maxRequestSize: 1000MB
y9:
    systemName: risedata-log
    internalIp: 192.168.x.x,10.0.x.x,172.20.x.x,10.192.x.x
    feature:
        jpa:
            packagesToScanEntityPublic: net.risesoft.y9public.entity
            packagesToScanEntityTenant: net.risesoft.entity
            packagesToScanRepositoryPublic: net.risesoft.y9public.repository
            packagesToScanRepositoryTenant: net.risesoft.repository
        security:
            enabled: true
            cors:
                allowCredentials: true
                allowedOriginPatterns:
                    - https://*.youshengyun.com
                    - http://*.youshengyun.com
                    - http://localhost:7056
                    - http://localhost:8080
                    - http://localhost:8081
                    - http://localhost:7070
                    - http://127.0.0.1:7055
                    - http://127.0.0.1:7056
            xss:
                ignoreParam:
                    - ID
                    - properties
            csrf:
                acceptedReferer:
                    - 127.0.0.1
                    - localhost
                    - vue.youshengyun.com
        oauth2:
            resource:
                enabled: true
                allowBasicAuthentication: true
                allowFormEncodedBodyParameter: true
                allowUriQueryParameter: true
                protectedUrlPatterns: /api/*
                opaque:
                    client-id: clientid_oidc
                    client-secret: secret_oidc
                    introspection-uri: https://test.youshengyun.com/sso/oidc/introspect
                    profile-uri: https://test.youshengyun.com/sso/oidc/profile