server:
    port: 7055
    servlet:
        register-default-servlet: true
        encoding:
            charset: UTF-8
            enabled: true
            force: true
        session:
            tracking-modes: COOKIE
    tomcat:
        uri-encoding: UTF-8
spring:
    application:
        name: risedata-master
    aop:
        auto: false
        proxy-target-class: false
    autoconfigure:
        exclude:
            - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
            - org.springframework.boot.autoconfigure.quartz.QuartzAutoConfiguration
            - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
            - org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration
            - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
    datasource:
        generate-unique-name: false
        type: com.alibaba.druid.pool.DruidDataSource
        druid:
            filter:
                stat:
                    log-slow-sql: true
                    mergeSql: true
                    slow-sql-millis: 3000
                wall:
                    config:
                        drop-table-allow: false
                    enabled: true
            stat-view-servlet:
                enabled: false
                url-pattern: /druid/*
                login-username: admin
                login-password: admin
                reset-enable: false
                allow: 127.0.0.1
            web-stat-filter:
                enabled: false
                url-pattern: /*
                exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*,/static/*'
            y9-public:
                #driver-class-name: oracle.jdbc.OracleDriver
                #url: jdbc:oracle:thin:@127.0.0.1:1521:orcl
                #username: Y9_PUBLIC
                #password: '111111'
                driver-class-name: com.mysql.cj.jdbc.Driver
                url: jdbc:mysql://localhost:3306/y9_data?serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true&useUnicode=true&characterEncoding=utf-8&rewriteBatchedStatements=true&useCompression=true&useSSL=false
                username: root
                password: '111111'
                initialSize: 1
                maxActive: 20
                maxPoolPreparedStatementPerConnectionSize: 100
                maxWait: 60000
                minEvictableIdleTimeMillis: 300000
                minIdle: 1
                poolPreparedStatements: true
                testOnBorrow: false
                testOnReturn: false
                testWhileIdle: true
                timeBetweenEvictionRunsMillis: 60000
                useGlobalDataSourceStat: true
                validationQuery: SELECT 1 FROM DUAL
    jmx:
        default-domain: dataflow
    jpa:
        hibernate:
            naming:
                implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        open-in-view: false
        properties:
            hibernate:
                cache:
                    use_query_cache: false
                    use_second_level_cache: false
                dialect: org.hibernate.dialect.MySQL8Dialect
                hbm2ddl:
                    auto: update
                jdbc:
                    batch_size: 100
                show_sql: false
    kafka:
        bootstrap-servers: localhost:9092
        producer:
            retries: 0
            batch-size: 16384
            buffer-memory: 33554432
        consumer:
            auto-commit-interval: 1000
            enable-auto-commit: true
            group-id: y9risedata-server
    main:
        allow-bean-definition-overriding: true
        allow-circular-references: true
    mvc:
        view:
            prefix: /WEB-INF/jsp/
            suffix: .jsp
    servlet:
        multipart:
            maxFileSize: 200MB
            maxRequestSize: 1000MB
y9:
    systemName: dataflow
    internalIp: 192.168.x.x,10.0.x.x,172.20.x.x,10.192.x.x
    service:
        org:
            directUrl: http://127.0.0.1:7055/platform
    common:
        convertEnabled: true
        environments: Public,dev
        kafkaEnabled: false
        logBaseUrl: http://127.0.0.1:7055/log
        orgBaseUrl: http://127.0.0.1:7055/platform
    feature:
        jpa:
            packagesToScanEntityPublic: net.risesoft.y9public.entity,net.risesoft.api.persistence.model,net.risesoft.security.model
            packagesToScanEntityTenant: net.risesoft.entity
            packagesToScanRepositoryPublic: net.risesoft.y9public.repository
            packagesToScanRepositoryTenant: net.risesoft.repository
        log:
            enabled: false
        security:
            enabled: true
            cors:
                allowCredentials: true
                allowedOriginPatterns:
                    - https://*.youshengyun.com
                    - http://*.youshengyun.com
                    - http://localhost:7056
                    - http://localhost:7055
                    - http://localhost:7070
                    - http://127.0.0.1:7055
                    - http://127.0.0.1:7056
            xss:
                ignoreParam:
                    - ID
                    - properties
                    - operationArray
                    - resourceInfoJson
                    - meta
                    - accessLogJson
                    - clickedAppJson
                    - departmentJson
                    - personJson
                    - groupJson
                    - positionJson
                    - url
                    - xmlData
                    - parseData
                    - whereSql
            csrf:
                acceptedReferer:
                    - 127.0.0.1
                    - localhost
        oauth2:
            resource:
                enabled: false
                allowBasicAuthentication: true
                allowFormEncodedBodyParameter: true
                allowUriQueryParameter: true
                protectedUrlPatterns: /api/*
                opaque:
                    client-id: clientid
                    client-secret: secret
                    introspection-uri: http://127.0.0.1:7055/sso/oauth2.0/introspect
                    profile-uri: http://127.0.0.1:7055/sso/oauth2.0/profile
rpc.port: 7066
#服务注册相关                    
beta:   
  service:
    watch:
      #刷新时间
      refreshTime: 10000
    #检查服务间隔 毫秒
    check: 30000
    #是否检查服务 心跳本地为false
    checkEnable: false
  discovery:
    #续订刷新时间 
    environment: Public
    heartBeat: 30000
    #刷新全部毫秒
    refreshAll: 60000
    listener: true
    managerInfo: 17620075923
    description: 调度管控中心
    version: 1.0.3
    ip: 127.0.0.1
    serverAddr: http://127.0.0.1:7055/    
  servers: rpc:127.0.0.1:7066    
net.risedata.jdbc.show.sql: false